### ISSUE TITLE
有个地方说反了

### ISSUE THREAD

**Issue by shookgao** [lilyvya/aria2-conf#1]
这儿应该说反了：
```
会在 dir 下生成同名.aria2文件，当 force-save=true 时完成时删除， force-save=false 时不删除
```
我实际使用中发现force-save=false时下载完成.aria2文件会自动删除，force-save=true 时下载完成还是会保留.aria2文件，我有强迫症，所以我都是设置的force-save=false

**Comment by lilyvia** [comment]
感谢指出，确实反了
